# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raphael Seher
email: raphael.seher@gmail.com
description: Raphael Seher is a app developer in Carinthia, Austria. Currently working at xamoom (xamoom.com). I'm interested in developing for iOS and Android, designing, UI/UX and photography.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.raphaelseher.at" # the base hostname & protocol for your site
twitter_username: raphaelseher
github_username:  raphaelseher

# Build settings
markdown: kramdown
