# Site settings
title: Raphael Seher
tagline: ""
url: "http://raphaelseher.at"
author_name: "Raphael Seher"

# Social
socialimg: /img/profil.jpg 
twitter: raphaelseher
github: raphaelseher
instagram: raphaelseher

# Contact
email: "raphael.seher@gmail.com" # This is my real email address. Please don't email me.

# Use this for production
sass:
  style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
